# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Run e2e tests
        run: mvn clean compile
      - uses: actions/upload-artifact@master
        with:
            name: maven artifacts
            path: target/
 

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - uses: actions/download-artifact@master
      with:
          name: maven artifacts
          path: target
    - name: Run e2e tests
      run: mvn surefire:test -Dheadless=true
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
        name: execution report
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit
